export const aroundTownEvents = [
  "Go see a movie",
  "Visit an art gallery",
  "Snag a new bottle of wine",
  "Comedy show",
  "Music venue or event",
  "Cooking class",
  "Attend a trivia night",
  "Go have a picnic",
  "farmer's market",
  "couples massages",
  "Attend a theater showing",
  "Visit a Food truck",
  "Attend a Pottery class",
  "Do a local/online scavenger hunt for your city",
  "Attend a music show",
  "escape room",
  "drive around town",
  "dance class",
  "explore a botanical garden",
  "scooter around or ride bikes at park",
  "Go watch a sports game",
  "Museum visit",
  "Rooftop dinner or dinner with views",
  "Attend a comedy improv show",
  "Outdoor wilderness activity",
  "Attend a poetry reading event",
  "Visit a local jazz or blues bar",
  "Hike at sunrise",
  "Attend a live magic show",
  "Mini golf and ice cream date",
  "Visit a board game café",
  "Outdoor concert in a local park",
  "Attend a wine and paint night",
  "Roller skating or ice skating",
  "Attend a local film festival",
  "Science museum exploration",
  "Take a cooking class together",
  "Bowling",
  "Go-kart racing for some adrenaline",
  "Attend a book reading or author event",
  "Visit a nearby planetarium",
  "Brewery tour and beer tasting",
  "Attend a live stand-up comedy show",
  "Yoga or fitness class for couples",
  "Outdoor hiking or nature walk",
  "Attend a themed costume party",
  "Volunteer together for a cause",
  "Attend a local poetry slam",
  "Go stargazing",
  "Sunset bike ride along a trail",
  "Free community outdoor concert",
  "Visit a local community garden",
  "Explore a nearby nature reserve",
  "Outdoor photography session",
  "Geocaching adventure in the city",
  "DIY outdoor painting session",
  "Visit a public park for a day out",
  "Art and craft fair in the park",
  "Explore a nearby historic district",
  "Attend a community garage sale",
  "Visit a nearby waterfall or creek",
  "Have a scenic bike or scooter ride",
  "Bird watching",
  "Have a picnic, but with homemade snacks",
  "Attend a local cultural festival",
  "Explore a nearby trail or hiking path",
  "Outdoor photography scavenger hunt",
  "Visit a local food truck event and try different things",
  "Go mural / graffiti hunting in the city or attend a local art event",
  "Visit a local community farm",
  "Explore a nearby sculpture garden",
  "Attend a community clean-up event",
  "Outdoor painting with sidewalk chalk",
  "Visit a nearby lake for fishing",
  "Play Frisbee or other two person activity at park",
  "Go visit some local shops",
  "Walk up at the capital",
  "Walk at a local park",
  "Visit plant store",
  "Walk around target or other store",
  "Go out and get ingredients for a creative meal at home",
  "Attend a drive-in movie theater",
  "Visit a new area of town",
];