export const atHomeEvents = [
  // Cooking Activities
  "Cook a new recipe together",
  "Have a homemade pizza night",
  "Bake and decorate cookies",
  "Create your own DIY sushi",
  "Build a DIY ice cream sundae bar",
  "Host a cooking competition",
  "Make breakfast for dinner",
  "Try a themed cooking night (e.g., Italian, Mexican)",
  "Create a custom cocktail or mocktail",
  "Make personalized DIY chocolate fondue",
  
  // Games/Board Games
  "Play classic board games together",
  "Try a new card game or learn card tricks",
  "Have a video game marathon",
  "Create your own trivia night",
  "Play a tabletop role-playing game",
  "Host a game night with friends online",
  "Try a two-player strategy game",
  "Build a puzzle together",
  "Create your own DIY board game",
  "Have a retro video game night",
  
  // Watching Shows/Movies
  "Have a movie marathon with a theme",
  "Start a new TV series together",
  "Watch each other's favorite childhood movies",
  "Have a documentary night",
  "Create a DIY home cinema experience",
  "Host a virtual movie night with friends",
  "Explore foreign films together",
  "Watch classic black-and-white movies",
  "Have a nostalgia night with old TV shows",
  "Create a personalized short film or video ;)",
  
  // Arts/Crafts
  "Paint or draw each other's portraits",
  "Make DIY personalized greeting cards",
  "Create a scrapbook of your favorite memories",
  "Craft DIY home decor together",
  "Try your hand at origami",
  "Make homemade candles",
  "Create tie-dye shirts or socks",
  "Build a terrarium or indoor garden",
  "Make your own DIY photo album",
  "Craft a DIY couple's vision board",
  
  // Other Indoor Couple Dates
  "Indoor picnic with favorite snacks",
  "Host a virtual game night with friends",
  "Create a custom playlist and dance together",
  "Have a themed costume night at home",
  "Build a blanket fort and have a cozy night",
  "Plan and book a future vacation together",
  "Try a home workout or yoga session",
  "Have a karaoke night at home",
  "Plan a DIY spa night",
  "Create a DIY escape room at home",
  
  // Additional Suggestions
  "Try a new hobby together (e.g., painting, photography)",
  "Read and discuss the same book",
  "Write a short story or poem together",
  "Learn a new language together",
  "Have a DIY home science experiment night",
  "Plan and design your dream home",
  "Take a virtual museum tour together",
  "Plan and cook a three-course meal together",
  "Write and perform a short play",
  "Create a shared online photo album",
  
  // More Indoor Couple Dates
  "Host a virtual double date with friends",
  "Have a technology-free night",
  "Take an online dance class together",
  "Plan and host a virtual party",
  "Build a puzzle or LEGO set together",
  "Create personalized playlists for each other",
  "Host a themed costume party at home",
  "Plan and record a podcast together",
  "Try a virtual reality experience",
  "Have a DIY karaoke night with online lyrics",
  
  // Final Set of Activities
  "Write love letters to each other",
  "Learn a magic trick and perform for each other",
  "Have a DIY at-home wine or beer tasting",
  "Host a virtual trivia night with friends",
  "Create a DIY indoor mini-golf course",
  "Have a themed indoor picnic",
  "Plan and create a vision board for the future",
  "Create a playlist of songs that represent your relationship",
  "Host a virtual escape room challenge",
  "Build a fort and have a storytelling night",

  "Language learning night",
  "DIY Science Experiments",
  "Start a book club and read the same book together",
  "Themed Dinner and Movie Night",
  "Memory Lane Night",
  "Gaming Marathon",
  "DIY Vision Board",
  "Host a DIY outdoor spa night",
  "Go for a walk around the neighborhood",
];